site_name: Mobile integron database

theme:
  name: material
  features:
    - content.code.copy

nav:
  - Welcome: index.md
  - Quickstart: quickstart.md
  - Tutorial: tutorial.md
  - Workflow: workflow.md

markdown_extensions:
  - attr_list
  - pymdownx.superfences

plugins:
  - search

extra_javascript:
  - https://code.jquery.com/jquery-3.7.1.min.js
  - https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js
  - js/tables.js

extra_css:
  - https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css

extra:
  include_files:
    - integronfinder_results_integrons.tsv
    - bakta_annotations.tsv
