site_name: Mobile integron database
theme:
  name: readthedocs

nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - Workflow: workflow.md

plugins:
  - search
  - table-reader

extra_css:
  - https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css

extra_javascript:
  - https://code.jquery.com/jquery-3.7.1.min.js
  - https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js
  - js/tables.js

extra:
  include_files:
    - combined_integronfinder_results_integrons.tsv
